/** 
* \file definitions.hpp
* \brief Definition des constantes du programme
* \author Louis Lesniak & Hugues Steiner
* \date 10 Nov. 2021
*/

#ifndef DEFINITIONS_HPP
#define DEFINITIONS_HPP

#define error(s) {\
        perror(s);\
        exit(EXIT_FAILURE); }

#endif


#define PI 3.14159

#define NOM_SAUVEGARDE "Save.txt"

/* Menu */

#define HAUTEUR_ECRAN_MENU 350
#define LARGEUR_ECRAN_MENU 250
#define NB_CATEG_MENU 3
#define CATEG_SAUVEGARDE 1
#define COULEUR_TEXTE_MENU {231, 76, 60, 255}
#define COULEUR_SAUVEGARDE_MANQUANTE {220, 220, 220, 255}
#define COULEUR_SELECTING {255, 0, 0, 255}

/* Jeu */

#define HAUTEUR_ECRAN 800
#define LARGEUR_ECRAN 800
#define TAILLE_POINTEUR_SOURIS 4

#define HAUTEUR_INTERFACE 90
#define ABSCISSE_INITIALE 100
#define NB_CLASSE_NAVIRE 3
#define ABSCISSE_INITIALE_SELECTION 500
#define NB_SELECTION_MAX 8
#define TAILLE_BOUTON 30
#define DUREE_EXPLOSION 700

#define TAILLE_ILE1 64
#define TAILLE_ILE2 64 // Bonus

#define PV_CONT_WIDTH 32
#define PV_CONT_HEIGHT 6
#define PV_REMP_WIDTH 30
#define PV_REMP_HEIGHT 4

//Flotte
#define OR_INITIAL 200
#define GAIN_INITIAL 1
#define OR_MAX 9999

#define NB_AMELIO_MAX 3

//Base
#define PV_MAX_BASE 5000
#define TAILLE_BASE 90
#define DEGATS_BASE 20
#define CADENCE_TIR_BASE 1
#define PORTEE_BASE 70

//Bateau
#define NB_CARAC_BATEAU 6

#define COUT_PATROUILLEUR 20
#define COUT_AMELIORATION_PATROUILLEUR 100
#define TAILLE_PATROUILLEUR 24
#define VITESSE_PATROUILLEUR 2
#define AMELIO_VITESSE_PATROUILLEUR 1
#define PV_MAX_PATROUILLEUR 20
#define AMELIO_PV_MAX_PATROUILLEUR 5
#define DEGATS_PATROUILLEUR 4
#define AMELIO_DEGATS_PATROUILLEUR 2
#define CADENCE_TIR_PATROUILLEUR 2
#define AMELIO_CADENCE_PATROUILLEUR 1
#define PORTEE_PATROUILLEUR 60
#define AMELIO_PORTEE_PATROUILLEUR 10

#define COUT_CROISEUR 50
#define COUT_AMELIORATION_CROISEUR 150
#define TAILLE_CROISEUR 32
#define VITESSE_CROISEUR 1
#define AMELIO_VITESSE_CROISEUR 1
#define PV_MAX_CROISEUR 50
#define AMELIO_PV_MAX_CROISEUR 8
#define DEGATS_CROISEUR 8
#define AMELIO_DEGATS_CROISEUR 3
#define CADENCE_TIR_CROISEUR 1
#define AMELIO_CADENCE_CROISEUR 0.5
#define PORTEE_CROISEUR 85
#define AMELIO_PORTEE_CROISEUR 15